version: '2'

services:
  wordpress:
    depends_on:
      - db
    restart: always
    image: wordpress:4.9.8-php7.1-apache
    volumes:
      - ./www:/var/www/html/
      - ./logs/apache/:/var/log/apache2/
    expose:
      - ${VIRTUAL_PORT}
    container_name: ${VIRTUAL_HOST}-wp
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  db:
    image: mysql:5.7
    container_name: ${VIRTUAL_HOST}-db
    restart: always
    expose:
      - 3306
    volumes:
      - ./database1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  pma:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:mysql
    container_name: ${VIRTUAL_HOST}-pma
    expose:
      - ${VIRTUAL_PORT}
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      VIRTUAL_HOST: pma.${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
  default:
    external:
      name: nginx-proxy
