version: '2'

services:
  wordpress:
    restart: always
    image: wordpress:4.9.8-php7.1-apache
    volumes:
      - ./www:/var/www/html/
      - ./logs/apache/:/var/log/apache2/
    external_links:
      - mysql-db
    expose:
      - ${VIRTUAL_PORT}
    container_name: ${VIRTUAL_HOST}-wp
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${VIRTUAL_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  node:
    restart: always
    container_name: ${VIRTUAL_HOST}-dev
    image: node:8
    environment:
      VIRTUAL_HOST: dev.${VIRTUAL_HOST}
      BROWSERSYNC_PROXY: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    links:
      - wordpress:${VIRTUAL_HOST}
    volumes:
      - ./www/wp-content/themes/${WORDPRESS_THEME_NAME}:/var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}
      - ./logs/node:/root/.npm/_logs
    working_dir: /var/www/html/wp-content/themes/${WORDPRESS_THEME_NAME}
    command: bash -c "npm install && npm install -g gulp && npm run dev"
    expose:
      - ${VIRTUAL_PORT}
networks:
  default:
    external:
      name: wp-dev-env
