# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

#project name
PROJECT:
  name: "Dissident Booster"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets"
  php:
    - "{*,**/*}.php"
    - "!node_modules/**"
    - "!.git/**"
  js:  "src/js/**/*.js"
  css: "src/scss/**/*.scss"
  img: "src/img/raw/*.{png,jpg,gif,svg}"

  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/app.js"
